// <auto-generated />
using System;
using ECommerceAPI.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceAPI.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = 1,
                            AddressLine1 = "123 Main Street",
                            City = "Ahmedabad",
                            Country = "India",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsDefault = true,
                            Landmark = "Near City Mall",
                            Phone = "9876543211",
                            Pincode = "380001",
                            ReceiverName = "Rahul Patel",
                            State = "Gujarat",
                            UserID = 2
                        },
                        new
                        {
                            AddressID = 2,
                            AddressLine1 = "456 Office Complex",
                            City = "Ahmedabad",
                            Country = "India",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsDefault = false,
                            Landmark = "Opposite Bank",
                            Phone = "9876543211",
                            Pincode = "380015",
                            ReceiverName = "Rahul Patel",
                            State = "Gujarat",
                            UserID = 2
                        },
                        new
                        {
                            AddressID = 3,
                            AddressLine1 = "789 Park Avenue",
                            City = "Surat",
                            Country = "India",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsDefault = true,
                            Landmark = "Near School",
                            Phone = "9876543212",
                            Pincode = "395001",
                            ReceiverName = "Priya Shah",
                            State = "Gujarat",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            UserID = 2
                        },
                        new
                        {
                            CartID = 2,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            UserID = 3
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("CartID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemID = 1,
                            CartID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Price = 25000.00m,
                            ProductID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            CartItemID = 2,
                            CartID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Price = 599.00m,
                            ProductID = 3,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemID = 3,
                            CartID = 2,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Price = 55000.00m,
                            ProductID = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Electronics",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Clothing",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Books",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Home & Kitchen",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            IsActive = true,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID", "ProductID")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<decimal?>("CouponDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("AddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            AddressID = 1,
                            CouponDiscount = 200.00m,
                            Created = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            DeliveryDate = new DateTime(2026, 3, 14, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            NetAmount = 25998.00m,
                            OrderDate = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            OrderNo = "ORD001",
                            Status = "Pending",
                            TotalAmount = 26198.00m,
                            UserID = 2
                        },
                        new
                        {
                            OrderID = 2,
                            AddressID = 3,
                            Created = new DateTime(2026, 3, 9, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            DeliveryDate = new DateTime(2026, 3, 13, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            NetAmount = 55000.00m,
                            OrderDate = new DateTime(2026, 3, 9, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            OrderNo = "ORD002",
                            Status = "Pending",
                            TotalAmount = 55000.00m,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("AddressID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            AddressID = 1,
                            Amount = 25000.00m,
                            Created = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Discount = 0.00m,
                            NetAmount = 25000.00m,
                            OrderID = 1,
                            ProductID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailID = 2,
                            AddressID = 1,
                            Amount = 1198.00m,
                            Created = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Discount = 0.00m,
                            NetAmount = 1198.00m,
                            OrderID = 1,
                            ProductID = 3,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailID = 3,
                            AddressID = 3,
                            Amount = 55000.00m,
                            Created = new DateTime(2026, 3, 9, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Discount = 0.00m,
                            NetAmount = 55000.00m,
                            OrderID = 2,
                            ProductID = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentModeID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.HasIndex("PaymentModeID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            Created = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            OrderID = 1,
                            PaymentModeID = 3,
                            PaymentReference = "UPI123456789",
                            PaymentStatus = "Completed",
                            TotalPayment = 25998.00m,
                            TransactionDate = new DateTime(2026, 3, 7, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            TransactionID = "TXN001"
                        },
                        new
                        {
                            PaymentID = 2,
                            Created = new DateTime(2026, 3, 9, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            OrderID = 2,
                            PaymentModeID = 1,
                            PaymentReference = "CC987654321",
                            PaymentStatus = "Completed",
                            TotalPayment = 55000.00m,
                            TransactionDate = new DateTime(2026, 3, 9, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            TransactionID = "TXN002"
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentModeID"));

                    b.Property<string>("PaymentModeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentModeID");

                    b.ToTable("PaymentModes");

                    b.HasData(
                        new
                        {
                            PaymentModeID = 1,
                            PaymentModeName = "Credit Card"
                        },
                        new
                        {
                            PaymentModeID = 2,
                            PaymentModeName = "Debit Card"
                        },
                        new
                        {
                            PaymentModeID = 3,
                            PaymentModeName = "UPI"
                        },
                        new
                        {
                            PaymentModeID = 4,
                            PaymentModeName = "Cash on Delivery"
                        },
                        new
                        {
                            PaymentModeID = 5,
                            PaymentModeName = "Net Banking"
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/smartphone.jpg",
                            IsActive = true,
                            Price = 25000.00m,
                            ProductCode = "ELEC001",
                            ProductName = "Smartphone",
                            StockQuantity = 0,
                            UserID = 4
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/laptop.jpg",
                            IsActive = true,
                            Price = 55000.00m,
                            ProductCode = "ELEC002",
                            ProductName = "Laptop",
                            StockQuantity = 0,
                            UserID = 4
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/tshirt.jpg",
                            IsActive = true,
                            Price = 599.00m,
                            ProductCode = "CLO001",
                            ProductName = "T-Shirt",
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 2,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/jeans.jpg",
                            IsActive = true,
                            Price = 1299.00m,
                            ProductCode = "CLO002",
                            ProductName = "Jeans",
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 3,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/book.jpg",
                            IsActive = true,
                            Price = 499.00m,
                            ProductCode = "BOOK001",
                            ProductName = "Programming Book",
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 4,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Image = "https://example.com/images/coffeemaker.jpg",
                            IsActive = true,
                            Price = 3499.00m,
                            ProductCode = "HK001",
                            ProductName = "Coffee Maker",
                            StockQuantity = 0,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerceAPI.Models.ProductReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("ECommerceAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserTypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("UserTypeID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "Admin Address, Ahmedabad",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Email = "admin@example.com",
                            IsActive = true,
                            Password = "$2a$11$3aVUHVwvrHny.ECgwf1DVe.QZkvBvbJlnULQg0Bw.TeyVFATmuZ/q",
                            Phone = "9876543210",
                            UserName = "Admin User",
                            UserTypeID = 1
                        },
                        new
                        {
                            UserID = 2,
                            Address = "123 Main Street, Ahmedabad",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Email = "rahul@example.com",
                            IsActive = true,
                            Password = "$2a$11$fB8lznovvFBQiDJYUGsPjegQB1C5/K5sLSoQpWuBFWbyFGJj0NDRa",
                            Phone = "9876543211",
                            UserName = "Rahul Patel",
                            UserTypeID = 2
                        },
                        new
                        {
                            UserID = 3,
                            Address = "456 Park Avenue, Surat",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Email = "priya@example.com",
                            IsActive = true,
                            Password = "$2a$11$zCdPhjC9h6H41anxSmNoROClaMgvpydtg1h5DS16VdJzC43kZpaLO",
                            Phone = "9876543212",
                            UserName = "Priya Shah",
                            UserTypeID = 2
                        },
                        new
                        {
                            UserID = 4,
                            Address = "789 Business Park, Vadodara",
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            Email = "seller@example.com",
                            IsActive = true,
                            Password = "$2a$11$90r7MeXtHE9HwllF7lPxIO8VvpbJw6bX2Y2F./rXwzPVxJn0jJ5RW",
                            Phone = "9876543213",
                            UserName = "Tech Seller",
                            UserTypeID = 3
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeID = 1,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            UserTypeID = 2,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            UserTypeName = "Customer"
                        },
                        new
                        {
                            UserTypeID = 3,
                            Created = new DateTime(2026, 3, 12, 12, 46, 39, 166, DateTimeKind.Local).AddTicks(8839),
                            UserTypeName = "Seller"
                        });
                });

            modelBuilder.Entity("ECommerceAPI.Models.Address", b =>
                {
                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Cart", b =>
                {
                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerceAPI.Models.Cart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.CartItem", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Favorite", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.OrderDetail", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("ECommerceAPI.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Payment", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("ECommerceAPI.Models.Payment", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.PaymentMode", "PaymentMode")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentModeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.User", null)
                        .WithMany("Payments")
                        .HasForeignKey("UserID");

                    b.Navigation("Order");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Product", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserID");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.ProductImage", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceAPI.Models.ProductReview", b =>
                {
                    b.HasOne("ECommerceAPI.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceAPI.Models.User", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceAPI.Models.User", b =>
                {
                    b.HasOne("ECommerceAPI.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceAPI.Models.PaymentMode", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ECommerceAPI.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Favorites");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("ECommerceAPI.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("ProductReviews");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceAPI.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
